- name: Generate configs
  template:
    src: "configs/{{ item }}"
    dest: "~/.{{ item }}"
    owner: root
    mode: u=rw,g=,o=
  with_items:
    - bash_aliases
    - bash_profile
    - gitconfig
    - bash_changes

- name: Apply some changes to bash
  lineinfile:
    path: ~/.bashrc
    line: . ~/.bash_changes

# - name: Download special templates for git shell improvements
#   get_url:
#     url: https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.prompt.sh
#     dest: ~/.git_shell

# We need to copy the configs for ubuntu users as well for development
- name: Generate configs for development
  template:
    src: "configs/{{ item }}"
    dest: "/home/ubuntu/.{{ item }}"
    owner: ubuntu
    mode: u=rw,g=,o=
  with_items:
    - bash_aliases
    - bash_profile
    - gitconfig
    - bash_changes
  when: is_dev


- name: Generate ssh config
  template:
    src: "configs/ssh_config"
    dest: "~/.ssh/config"
    owner: ubuntu
    mode: u=rw,g=,o=
  with_items:
    - ssh_config
  when: is_dev


- name: Generate ssh config
  template:
    src: "configs/ssh_config"
    dest: "/root/.ssh/config"
    owner: root
    mode: u=rw,g=,o=
  with_items:
    - ssh_config
  when: is_dev
