- name: Generate configs
  template:
    src: "configs/{{ item }}"
    dest: "~/.{{ item }}"
    owner: root
    mode: u=rw,g=,o=
  with_items:
    - bash_aliases
    - bash_profile
    - gitconfig
    - bash_changes

- name: Apply some changes to bash
  lineinfile:
    path: ~/.bashrc
    line: . ~/.bash_changes
