- name: Ensure that required dirs exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
    - "{{ logs_path }}"
    - "{{ cron_path }}"

- name: Generate cron scripts
  template:
    src: "{{ item }}"
    dest: "{{ scripts_path }}/{{ item }}"
    mode: u=rwx,g=,o=
  with_items:
    - "mysql_backup.sh"
    - "google_drive_backup.sh"
    - "reboot_if_needed.sh"
    - "backup.sh"

- name: Generate cron scripts
  template:
    src: "backup_cron.sh"
    dest: "{{ cron_path }}/backup.sh"
    mode: u=rwx,g=,o=

# We also reboot if needed right after backup.
# So backup goes in 3 steps. DB dump, file sync with the cloud, reboot if needed.
- name: Ensure that we have a cron job for backup
  cron:
    name: backup
    special_time: daily
    state: present
    user: root
    job: "{{ scripts_path }}/backup_cron.sh"
