- include: packages.yml
- include: scripts.yml
- include: configs.yml

- include: cron.yml
  when: is_prod

- name: Set timezone
  command: "timedatectl set-timezone {{ timezone }}"

- name: Install "bower" node.js package globally.
  npm: name=bower global=yes

- name: Fix locale
  command: "update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8"

- name: Install ansible-vault
  pip:
    name: "{{ item }}"
  with_items:
    - ansible-vault
    - ipdb

- name: Ensure required services are enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ common_enabled_services }}"


# - name: Do we have ssh key?
#   stat: path="{{ ssh_key_path }}"
#   register: ssh_key_stat

# - name: Generate key
#   command: "ssh-keygen -t rsa -C {{ email }} -f {{ ssh_key_path }} -N ''"
#   when: not ssh_key_stat.stat.exists
