---
- name: Generate scripts
  template:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item }}"
    mode: u=rwx,g=,o=
  with_items:
    - "deploy.sh"
    - "workon.sh"

- name: Generate scripts for development
  template:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item }}"
    mode: u=rwx,g=,o=
  with_items:
    - "develop.sh"
    - "tox.sh"
    - "clean.sh"
    - "makemessages.sh"

  when: is_dev

- name: Generate scripts for production
  template:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item }}"
    mode: u=rwx,g=,o=
  with_items:
    - "deploy_desecho.org.sh"
    - "restart.sh"
    - "debug.sh"
  when: is_prod
