# For root:
- name: Generate configs
  template:
    src: "configs/{{ item }}"
    dest: "/root/.{{ item }}"
    owner: root
    mode: u=rw,g=,o=
  with_items:
    - bash_aliases
    - bash_profile
    - gitconfig
    - bash_changes

- name: Apply some changes to bash
  lineinfile:
    path: /root/.bashrc
    line: . /root/.bash_changes

- name: Generate ssh config
  template:
    src: "configs/ssh_config"
    dest: "/root/.ssh/config"
    owner: root
    mode: u=rw,g=,o=
  with_items:
    - ssh_config
  when: is_dev

# For regular user:

# We need to copy the configs for ubuntu users as well for development
- name: Generate configs for development
  template:
    src: "configs/{{ item }}"
    dest: "{{ original_home }}/.{{ item }}"
    owner: "{{ user }}"
    mode: u=rw,g=,o=
  with_items:
    - bash_aliases
    - bash_profile
    - gitconfig
    - bash_changes
  when: is_dev

- name: Generate ssh config
  template:
    src: "configs/ssh_config"
    dest: "{{ home }}/.ssh/config"
    owner: "{{ user }}"
    mode: u=rw,g=,o=
  with_items:
    - ssh_config
  when: is_dev

- name: Apply some changes to bash
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: ". {{ home }}/.bash_changes"

- name: Make sure octopress works
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'
  when: desktop
