- include: packages.yml
- include: python36.yml
  when: install_python_3
- include: scripts.yml
- include: configs.yml
- include: pip.yml

- include: cron.yml
  when: is_prod

- name: Set timezone
  command: "timedatectl set-timezone {{ timezone }}"

- name: Check if npm is installed
  stat:
    path: /usr/bin/npm
  register: npm_binary

- name: Install npm
  shell: npm -g install npm
  when: not npm_binary.stat.exists

- name: Fix locale
  command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

- name: Ensure required services are enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ enabled_services }}"

- name: Make sure we have ubuntu host for our vm
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 ubuntu
  when: is_dev
