- include_tasks: packages.yml
- include_tasks: scripts.yml
- include_tasks: configs.yml
- include_tasks: pip.yml

- include_tasks: cron.yml
  when: is_prod

- name: Set timezone
  command: "timedatectl set-timezone {{ timezone }}"

- name: Install npm
  shell: "npm -g install npm@{{ npm_version }}"

- name: Fix locale
  command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

- name: Ensure required services are enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ enabled_services }}"

- name: Make sure we have ubuntu host for our vm
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 ubuntu
  when: is_dev
