- name: Install/Upgrade global pip packages
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  with_items:
    - pip
    - ansible-vault
    - ipdb
    - pdbpp

- name: Install/Upgrade global pip packages for development
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  with_items:
    - tox
    - isort
    - yapf
  when: is_dev