- name: Install/Upgrade global pip packages
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  with_items:
    - pip
    - ansible-vault
    - ipdb
    - pdbpp
    - virtualenv
    - six

- name: Install/Upgrade global pip packages
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  with_items:
    - unify
  when: is_dev

- name: Install/Upgrade global pip packages for development
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
    executable: pip3
  with_items:
    - tox
    - isort
    - yapf
    - autoflake
  when: is_dev
