- name: Add repository for python 3.6 installation
  shell: add-apt-repository ppa:jonathonf/python-3.6 -y

- name: apt-get update
  apt: update_cache=yes

- name: Ensure python 3.6 is installed
  apt: "name={{ item }} state=present"
  with_items:
    - python3.6
    - python3.6-dev

- name: Ensure python 3.6 is used. Step 1
  shell: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1

- name: Ensure python 3.6 is used. Step 2
  shell: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
