- name: Ensure hugo is installed
  apt: name=hugo state=present
  when: is_dev
  become: yes

- name: Generate scripts
  template:
    src: "{{ item }}"
    owner: "{{ user }}"
    dest: "{{ scripts_path }}/{{ item }}"
    mode: u=rwx,g=,o=
  with_items:
    - blog_deploy.sh
    - blog_post.sh
    - blog_preview.sh
