- name: Add remove_unused_movies command to cron
  cron:
    name: remove_unused_movies
    special_time: monthly
    state: present
    user: root
    job: "{{ cron_path }}/remove_unused_movies.sh"

- name: Add update_movie_data command to cron
  cron:
    name: update_movie_data
    special_time: yearly
    state: present
    user: root
    job: "{{ cron_path }}/update_movie_data.sh"

- name: Add update_imdb_ratings command to cron
  cron:
    name: update_imdb_ratings
    special_time: monthly
    state: present
    user: root
    job: "{{ cron_path }}/update_imdb_ratings.sh"

- name: Add update_vk_avatars command to cron
  cron:
    name: update_vk_avatars
    special_time: daily
    state: present
    user: root
    job: "{{ cron_path }}/update_vk_avatars.sh"
