- name: Generate command
  template:
    src: command.sh
    dest: "{{ cron_path }}/remove_unused_movies.sh"
    mode: u=rwx,g=,o=
  vars:
    command: remove_unused_movies
    track_code: "{{ track_code_remove_unused_movies }}"

- name: Generate command
  template:
    src: command.sh
    dest: "{{ cron_path }}/update_movie_data.sh"
    mode: u=rwx,g=,o=
  vars:
    command: update_movie_data
    track_code: "{{ track_code_update_movie_data }}"

- name: Generate command
  template:
    src: command.sh
    dest: "{{ cron_path }}/update_imdb_ratings.sh"
    mode: u=rwx,g=,o=
  vars:
    command: update_imdb_ratings
    track_code: "{{ track_code_update_imdb_ratings }}"
