- include: cron_scripts.yml
  when: is_prod

- include: cron.yml
  when: is_prod

- name: Create cache directory
  file: path={{ cache_path }} state=directory owner=root group=root

- name: Create cache file
  file: path={{ cache_path }}/tmdb3.cache state=touch owner=root group=root mode=0777
