email: desecho@gmail.com
full_name: Anton Samarchyan

scripts_path: "{{ home }}/scripts"
logs_path: "{{ home }}/logs"
cron_path: "{{ scripts_path }}/cron"

nodejs_version: "7.x"

nodejs_npm_global_packages:
  - name: bower
    version: 1.8.0
