mysql_user_password: "{{ mysql_root_password }}"
django_name: ghcontrib

nodejs_package_json_path: "{{ home }}/{{ django_name }}"
django_project_symlink_dest: "{{ nodejs_package_json_path }}"
# django_env: "{{ nodejs_package_json_path }}/env"

django_src_path: "{{ django_project_path }}"
django_settings_path: "{{ django_src_path }}/{{ django_project_name }}_project"


django_project_name: "{{ django_name }}"
django_env_settings_extra: |
  ADMIN_NAME = '{{ full_name }}'
  ADMIN_EMAIL = '{{ email }}'

  SOCIAL_AUTH_GITHUB_KEY = '{{ gh_key }}'
  SOCIAL_AUTH_GITHUB_SECRET = '{{ gh_secret }}'

  INTERNAL_IPS = []
  # INTERNAL_IPS = ['10.0.0.1']
