mysql_user_password: "{{ mysql_root_password }}"
django_name: ighelper

django_project_symlink_dest: "{{ home }}/{{ django_name }}"

django_src_path: "{{ django_project_path }}"
django_project_name: "{{ django_name }}_project"
django_env_settings_extra: |
  ADMIN_EMAIL = '{{ email }}'

  RAVEN_DSN = '{{ raven_dsn }}'
  DESECHO8653_PASSWORD = '{{ desecho8653_password }}'

  INTERNAL_IPS = []
  # INTERNAL_IPS = ['10.0.0.1']

yarn: yes
