prod_hostname: desecho.org

nodejs_npm_global_packages:
  - name: npm
  - name: yarn
  - name: npm-check-updates
  - name: csscomb
  - name: csscomb-linter
  - name: js-beautify
  - name: eslint-config-google
  - name: eslint-plugin-vue
  - name: eslint
