# Ansible's apt module requires aptitude and python-apt. The two tasks below fix that.
- name: Do we have aptitude?
  stat: path=/usr/bin/aptitude
  register: aptitude_stat

- name: Ensure that requirements for the apt action are present
  shell: apt-get update && apt-get install -y python-apt aptitude
  when: not aptitude_stat.stat.exists

- name: apt-get update/upgrade
  apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: Ensure required packages are present
  apt: "name={{ item }} state=present"
  with_items: "{{ required_packages }}"

- name: Install Chromium
  apt: "name=chromium-browser state=present"
  when: install_chromium

- name: Install PyCharm
  block:
    - name: Download and extract PyCharm
      unarchive:
        src: "https://download.jetbrains.com/python/pycharm-professional-{{ pycharm_version }}.tar.gz"
        dest: /opt
        remote_src: yes

    - name: Create symlink
      file:
        src: "/opt/pycharm-{{ pycharm_version }}/bin/pycharm.sh"
        dest: /usr/local/bin/pycharm
        state: link

    - name: Add Pycharm to launcher
      template:
        src: pycharm.desktop
        dest: "{{ home }}/.local/share/applications/pycharm.desktop"
        owner: "{{ user}}"
        mode: u=rw,g=,o=

  when: install_pycharm

- name: Install Sublime Text 3
  block:
    - name: Add apt source
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://download.sublimetext.com/ apt/stable/
      register: aptsource

    - name: Add apt key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present
      register: aptkey

    - apt: update_cache=yes
      when: aptkey.changed or aptsource.changed

    - name: Install Sublime Text
      apt: "name=sublime-text state=present"
  when: install_sublime
