- name: Install blog.desecho.org
  hosts: localhost

  vars_files:
      - vars/prod.yml
      - vars/common.yml
      - vars/blog_prod.yml
      - vars/site.yml

  roles:
    - acme-nginx
    - nginx-site
