- name: Initialize ubuntu machine for development
  hosts: localhost

  vars_files:
      - vars/dev.yml
      - vars/common.yml
      - vars/init.yml

  roles:
    - nodejs
    - swapfile
    - init
