- name: Initialize nginx server for production
  hosts: localhost

  vars_files:
      - vars/prod.yml
      - vars/common.yml
      - vars/init.yml
      - vars/init_prod.yml
      - vars/init_prod_secrets.yml

  roles:
    - nodejs
    - swapfile
    - init
    - nginx
    - fail2ban
