- name: Initialize nginx server for production
  hosts: localhost

  vars_files:
      - vars/prod.yml
      - vars/common.yml
      - vars/init.yml

  roles:
    - nodejs
    - swapfile
    - common
    - nginx
    - fail2ban
