- name: Install a fully functional uWSGI/nginx server for Django deployment on production. Movies Project.
  hosts: localhost

  vars_files:
      - vars/prod.yml
      - vars/common.yml
      - vars/movies_prod_secrets.yml
      - vars/movies.yml
      - vars/movies_prod.yml
      - vars/site.yml
      - vars/django.yml

  roles:
    - role: mysql
      become: yes
    - acme-nginx
    - django
    - movies
