- name: Install a fully functional uWSGI/nginx server for Django deployment
  hosts: localhost

  vars_files:
      - vars/movies_dev_secrets.yml
      - vars/movies.yml
      - vars/movies_dev.yml
      - vars/common.yml

  roles:
    - common
    - role: mysql
      become: yes
    - nginx
    - django
