- name: Install Django development environment. Movies Project.
  hosts: localhost
  become: yes

  vars_files:
      - vars/dev.yml
      - vars/common.yml
      - vars/desktop.yml
      - vars/movies_dev_secrets.yml
      - vars/movies.yml
      - vars/movies_dev.yml
      - vars/django.yml

  roles:
    - role: mysql
      become: yes
    - django
    - movies
