- name: Install a fully functional uWSGI/nginx server for Django deployment on development. Movies Project.
  hosts: localhost

  vars_files:
      - vars/dev.yml
      - vars/common.yml
      - vars/movies_dev_secrets.yml
      - vars/movies.yml
      - vars/movies_dev.yml
      - vars/django.yml

  roles:
    - nodejs
    - role: mysql
      become: yes
    - django
    - movies
