- name: Install Django development environment. PyFavorite Project.
  hosts: localhost

  vars_files:
      - vars/dev.yml
      - vars/common.yml
      - vars/pyfavorite.yml
      - vars/pyfavorite_dev.yml
      - vars/django.yml

  roles:
    - nodejs
    - role: mysql
      become: yes
    - django
