- name: Install a fully functional Uwsgi/nginx server for Django deployment
  hosts: localhost

  pre_tasks:
    - include_vars: vars.yml
  roles:
    - common
    - role: mysql
      become: yes
    - nginx
    # - acme-nginx
    # - django
