- name: Install desecho.org
  hosts: localhost

  vars_files:
      - vars/prod.yml
      - vars/common.yml
      - vars/desecho.org.yml
      - vars/site.yml

  roles:
    - acme-nginx
    - nginx-site
    - desecho.org
