email: desecho@gmail.com
user: ubuntu

mysql_root_password: password
mysql_user_password: "{{ mysql_root_password }}"

django_name: project
django_domain_name: project.local

django_debug: yes
django_user: root
django_project_symlink_dest: "/vagrant/project"

django_dbpass: password
django_secret_key: key
